package clases;

import javax.swing.JFrame;
import javax.swing.UIManager;


/**
 *
 * @author Sergio
 */
public class Interfaz extends javax.swing.JFrame {
    private Datos calculadora = new Datos();
    
    public Interfaz() {
        initComponents();
        
        jbOn.setVisible(true);
        pantalla.setVisible(false);
        jbOff.setVisible(false);
        boton9.setVisible(false);
        boton8.setVisible(false);
        boton7.setVisible(false);
        boton6.setVisible(false);
        boton5.setVisible(false);
        boton4.setVisible(false);
        boton3.setVisible(false);
        boton2.setVisible(false);
        boton1.setVisible(false);
        boton0.setVisible(false);
        jbSen.setVisible(false);
        jbCos.setVisible(false);
        jbTan.setVisible(false);
        jbLn.setVisible(false);
        jbCuadrado.setVisible(false);
        jbCubo.setVisible(false);
        jbCubo.setVisible(false);
        jbFactorial.setVisible(false);
        jbLog.setVisible(false);
        jbi.setVisible(false);
        jbRaiz.setVisible(false);
        jbElevado.setVisible(false);
        jbFraccion.setVisible(false);
        botonReset.setVisible(false);
        botonReset1.setVisible(false);
        botonParenD.setVisible(false);
        botonParenI.setVisible(false);
        botonMult.setVisible(false);
        botonDiv.setVisible(false);
        botonPunto.setVisible(false);
        botonIgual.setVisible(false);
        botonSum.setVisible(false);
        botonRes.setVisible(false);
        botonAyuda.setVisible(false);
        
        //calculadora.asignar(calculadoraDatos);
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pantalla = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbOn = new javax.swing.JButton();
        botonAyuda = new javax.swing.JButton();
        jbOff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbSen = new javax.swing.JButton();
        jbCos = new javax.swing.JButton();
        jbTan = new javax.swing.JButton();
        jbLn = new javax.swing.JButton();
        jbCuadrado = new javax.swing.JButton();
        jbCubo = new javax.swing.JButton();
        jbFactorial = new javax.swing.JButton();
        jbLog = new javax.swing.JButton();
        jbi = new javax.swing.JButton();
        jbRaiz = new javax.swing.JButton();
        jbElevado = new javax.swing.JButton();
        jbFraccion = new javax.swing.JButton();
        botonOperacion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();
        botonReset1 = new javax.swing.JButton();
        botonParenI = new javax.swing.JButton();
        botonParenD = new javax.swing.JButton();
        botonMult = new javax.swing.JButton();
        botonDiv = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonSum = new javax.swing.JButton();
        botonRes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });

        jbOn.setBackground(new java.awt.Color(255, 0, 0));
        jbOn.setText("ON");
        jbOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOnActionPerformed(evt);
            }
        });

        botonAyuda.setBackground(new java.awt.Color(255, 51, 0));
        botonAyuda.setText("AYUDA");
        botonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });

        jbOff.setBackground(new java.awt.Color(255, 0, 0));
        jbOff.setText("OFF");
        jbOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOffActionPerformed(evt);
            }
        });

        jbSen.setBackground(new java.awt.Color(0, 0, 0));
        jbSen.setForeground(new java.awt.Color(255, 255, 255));
        jbSen.setText("sin");

        jbCos.setBackground(new java.awt.Color(0, 0, 0));
        jbCos.setForeground(new java.awt.Color(255, 255, 255));
        jbCos.setText("cos");

        jbTan.setBackground(new java.awt.Color(0, 0, 0));
        jbTan.setForeground(new java.awt.Color(255, 255, 255));
        jbTan.setText("tan");
        jbTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTanActionPerformed(evt);
            }
        });

        jbLn.setBackground(new java.awt.Color(0, 0, 0));
        jbLn.setForeground(new java.awt.Color(255, 255, 255));
        jbLn.setText("ln");

        jbCuadrado.setBackground(new java.awt.Color(0, 0, 0));
        jbCuadrado.setForeground(new java.awt.Color(255, 255, 255));
        jbCuadrado.setText("x^2");

        jbCubo.setBackground(new java.awt.Color(0, 0, 0));
        jbCubo.setForeground(new java.awt.Color(255, 255, 255));
        jbCubo.setText("x^3");

        jbFactorial.setBackground(new java.awt.Color(0, 0, 0));
        jbFactorial.setForeground(new java.awt.Color(255, 255, 255));
        jbFactorial.setText("x!");

        jbLog.setBackground(new java.awt.Color(0, 0, 0));
        jbLog.setForeground(new java.awt.Color(255, 255, 255));
        jbLog.setText("log");

        jbi.setBackground(new java.awt.Color(0, 0, 0));
        jbi.setForeground(new java.awt.Color(255, 255, 255));
        jbi.setText("i");

        jbRaiz.setBackground(new java.awt.Color(0, 0, 0));
        jbRaiz.setForeground(new java.awt.Color(255, 255, 255));
        jbRaiz.setText("RAÍZ");

        jbElevado.setBackground(new java.awt.Color(0, 0, 0));
        jbElevado.setForeground(new java.awt.Color(255, 255, 255));
        jbElevado.setText("^");

        jbFraccion.setBackground(new java.awt.Color(0, 0, 0));
        jbFraccion.setForeground(new java.awt.Color(255, 255, 255));
        jbFraccion.setText("ab/c");
        jbFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFraccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jbSen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbElevado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbLn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSen)
                    .addComponent(jbCos)
                    .addComponent(jbTan)
                    .addComponent(jbLn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCuadrado)
                    .addComponent(jbCubo)
                    .addComponent(jbFactorial)
                    .addComponent(jbLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbi)
                    .addComponent(jbRaiz)
                    .addComponent(jbElevado)
                    .addComponent(jbFraccion))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        botonOperacion.setText("OPERACIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jbOff)
                .addGap(75, 75, 75)
                .addComponent(botonOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbOn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(botonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOn)
                    .addComponent(jbOff)
                    .addComponent(botonOperacion))
                .addGap(18, 18, 18)
                .addComponent(botonAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        boton7.setBackground(new java.awt.Color(255, 255, 255));
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setBackground(new java.awt.Color(255, 255, 255));
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setBackground(new java.awt.Color(255, 255, 255));
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton4.setBackground(new java.awt.Color(255, 255, 255));
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setBackground(new java.awt.Color(255, 255, 255));
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton6.setBackground(new java.awt.Color(255, 255, 255));
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton1.setBackground(new java.awt.Color(255, 255, 255));
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setBackground(new java.awt.Color(255, 255, 255));
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setBackground(new java.awt.Color(255, 255, 255));
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        botonReset.setBackground(new java.awt.Color(0, 0, 0));
        botonReset.setForeground(new java.awt.Color(255, 255, 255));
        botonReset.setText("CE");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        botonReset1.setBackground(new java.awt.Color(0, 0, 0));
        botonReset1.setForeground(new java.awt.Color(255, 255, 255));
        botonReset1.setText("C");
        botonReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReset1ActionPerformed(evt);
            }
        });

        botonParenI.setBackground(new java.awt.Color(0, 0, 0));
        botonParenI.setForeground(new java.awt.Color(255, 255, 255));
        botonParenI.setText("(");
        botonParenI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParenIActionPerformed(evt);
            }
        });

        botonParenD.setBackground(new java.awt.Color(0, 0, 0));
        botonParenD.setForeground(new java.awt.Color(255, 255, 255));
        botonParenD.setText(")");
        botonParenD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParenDActionPerformed(evt);
            }
        });

        botonMult.setBackground(new java.awt.Color(0, 0, 0));
        botonMult.setForeground(new java.awt.Color(255, 255, 255));
        botonMult.setText("X");
        botonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultActionPerformed(evt);
            }
        });

        botonDiv.setBackground(new java.awt.Color(0, 0, 0));
        botonDiv.setForeground(new java.awt.Color(255, 255, 255));
        botonDiv.setText("/");
        botonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivActionPerformed(evt);
            }
        });

        boton0.setBackground(new java.awt.Color(255, 255, 255));
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonPunto.setBackground(new java.awt.Color(0, 0, 0));
        botonPunto.setForeground(new java.awt.Color(255, 255, 255));
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });

        botonIgual.setBackground(new java.awt.Color(0, 0, 0));
        botonIgual.setForeground(new java.awt.Color(255, 255, 255));
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });

        botonSum.setBackground(new java.awt.Color(0, 0, 0));
        botonSum.setForeground(new java.awt.Color(255, 255, 255));
        botonSum.setText("+");
        botonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumActionPerformed(evt);
            }
        });

        botonRes.setBackground(new java.awt.Color(0, 0, 0));
        botonRes.setForeground(new java.awt.Color(255, 255, 255));
        botonRes.setText("-");
        botonRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReset, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(botonParenI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonReset1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(botonParenD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton7)
                    .addComponent(boton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonParenD)
                    .addComponent(botonParenI)
                    .addComponent(boton6)
                    .addComponent(boton5)
                    .addComponent(boton4))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMult)
                    .addComponent(boton3)
                    .addComponent(boton2)
                    .addComponent(boton1)
                    .addComponent(botonDiv))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton0)
                    .addComponent(botonPunto)
                    .addComponent(botonIgual)
                    .addComponent(botonSum)
                    .addComponent(botonRes))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pantalla)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOffActionPerformed
        dispose();
    }//GEN-LAST:event_jbOffActionPerformed

    private void jbTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTanActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        pantalla.setText(pantalla.getText() + "9");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton9ActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        pantalla.setText("");
                //calculadora.limpiar();
                //existePunto=false;
                pantalla.requestFocus();
    }//GEN-LAST:event_botonResetActionPerformed

    private void botonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResActionPerformed
        //if (!pantalla.getText().isEmpty()) {
                     //if (calculadora.num1.isEmpty()){
                     //calculadora.operacion(pantalla.getText(), "-");
                     //}
                     //else{
                     //calculadora.operacion(calculadora.realizarOperacion(pantalla.getText()), "-");
                     //} 
                //}
                pantalla.setText("");
                pantalla.requestFocus();
    }//GEN-LAST:event_botonResActionPerformed

    private void jbFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFraccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFraccionActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
         pantalla.setText(pantalla.getText() + "7");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        pantalla.setText(pantalla.getText() + "8");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton8ActionPerformed

    private void botonReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReset1ActionPerformed
        //if (!pantalla.getText().isEmpty()){
                    String cadena = pantalla.getText();
                    String borrado = cadena.substring(cadena.length()-1, cadena.length());
                    cadena = cadena.substring(0, cadena.length() - 1);
                    pantalla.setText(cadena);
                    
                    //if (".".equals(borrado))
                        //existePunto=false;
                //}
                pantalla.requestFocus();
    }//GEN-LAST:event_botonReset1ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        pantalla.setText(pantalla.getText() + "4");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        pantalla.setText(pantalla.getText() + "5");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        pantalla.setText(pantalla.getText() + "6");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton6ActionPerformed

    private void botonParenIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParenIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonParenIActionPerformed

    private void botonParenDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParenDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonParenDActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        pantalla.setText(pantalla.getText() + "1");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        pantalla.setText(pantalla.getText() + "2");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        pantalla.setText(pantalla.getText() + "3");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton3ActionPerformed

    private void botonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultActionPerformed
        if (!pantalla.getText().isEmpty()) {
                     //if (calculadora.num1.isEmpty()){
                     //calculadora.operacion(pantalla.getText(), "*");
                     }
                     //else{
                     //calculadora.operacion(calculadora.realizarOperacion(pantalla.getText()), "*");
                     //}
                    
                //}
                pantalla.setText("");
                pantalla.requestFocus();
    }//GEN-LAST:event_botonMultActionPerformed

    private void botonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivActionPerformed
        //if (calculadora.num1.isEmpty()){
                     //calculadora.operacion(pantalla.getText(), "/");
                     //}
                     //else{
                     //calculadora.operacion(calculadora.realizarOperacion(pantalla.getText()), "/");
                     //}
                    
                //}
                pantalla.setText("");
                pantalla.requestFocus();
    }//GEN-LAST:event_botonDivActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        pantalla.setText(pantalla.getText() + "0");
                pantalla.requestFocus();
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        String aux = pantalla.getText();
                
                //if (aux.isEmpty()){
                    pantalla.setText("0.");
                    //existePunto = true;
                //}
                //else if (existePunto==true){
               
                //}
                //else {
                    pantalla.setText(aux+".");
                    //existePunto=true;
                //}
                pantalla.requestFocus();
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        //if (!pantalla.getText().isEmpty()) {
                    //pantalla.setText(calculadora.realizarOperacion(pantalla.getText()));
                //}
                pantalla.requestFocus();
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumActionPerformed
        //if (!pantalla.getText().isEmpty()) {
                     //if (calculadora.num1.isEmpty()){
                     //calculadora.operacion(pantalla.getText(), "+");
                     //}
                     //else{
                     //calculadora.operacion(calculadora.realizarOperacion(pantalla.getText()), "+");
                     //}
                    
                //}
                pantalla.setText("");
                pantalla.requestFocus();
    }//GEN-LAST:event_botonSumActionPerformed

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed
        Ayuda ayuda = new Ayuda();
        ayuda.setVisible(true);
    }//GEN-LAST:event_botonAyudaActionPerformed

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        botonIgual.doClick();
    }//GEN-LAST:event_pantallaActionPerformed

    private void jbOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOnActionPerformed
        jbOn.setVisible(false);
        jbOff.setVisible(true);
        pantalla.setVisible(true);
        boton9.setVisible(true);
        boton8.setVisible(true);
        boton7.setVisible(true);
        boton6.setVisible(true);
        boton5.setVisible(true);
        boton4.setVisible(true);
        boton3.setVisible(true);
        boton2.setVisible(true);
        boton1.setVisible(true);
        boton0.setVisible(true);
        jbSen.setVisible(true);
        jbCos.setVisible(true);
        jbTan.setVisible(true);
        jbLn.setVisible(true);
        jbCuadrado.setVisible(true);
        jbCubo.setVisible(true);
        jbCubo.setVisible(true);
        jbFactorial.setVisible(true);
        jbLog.setVisible(true);
        jbi.setVisible(true);
        jbRaiz.setVisible(true);
        jbElevado.setVisible(true);
        jbFraccion.setVisible(true);
        botonReset.setVisible(true);
        botonReset1.setVisible(true);
        botonParenD.setVisible(true);
        botonParenI.setVisible(true);
        botonMult.setVisible(true);
        botonDiv.setVisible(true);
        botonPunto.setVisible(true);
        botonIgual.setVisible(true);
        botonSum.setVisible(true);
        botonRes.setVisible(true);
        botonAyuda.setVisible(true);
    }//GEN-LAST:event_jbOnActionPerformed

    @SuppressWarnings("unchecked")
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
            });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonAyuda;
    private javax.swing.JButton botonDiv;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMult;
    private javax.swing.JButton botonOperacion;
    private javax.swing.JButton botonParenD;
    private javax.swing.JButton botonParenI;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRes;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonReset1;
    private javax.swing.JButton botonSum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbCos;
    private javax.swing.JButton jbCuadrado;
    private javax.swing.JButton jbCubo;
    private javax.swing.JButton jbElevado;
    private javax.swing.JButton jbFactorial;
    private javax.swing.JButton jbFraccion;
    private javax.swing.JButton jbLn;
    private javax.swing.JButton jbLog;
    private javax.swing.JButton jbOff;
    private javax.swing.JButton jbOn;
    private javax.swing.JButton jbRaiz;
    private javax.swing.JButton jbSen;
    private javax.swing.JButton jbTan;
    private javax.swing.JButton jbi;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
